version: "3.7"
services:

    compiler:
        image: node:14.10.1-alpine3.12
        restart: unless-stopped
        user: node
        working_dir: /home/node
        volumes:
            - "./app/:/home/node"
        command: npx tsc -w

    app:
        image: node:14.10.1-alpine3.12
        restart: unless-stopped
        user: node
        working_dir: /home/node
        volumes:
            - "./app/:/home/node"
        command: tail -F .gitignore
        depends_on:
            - compiler

