version: "3.7"
services:

    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        restart: unless-stopped
        user: 1000:1000
        volumes:
            - "./app/:/usr/src/app"

